#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: INCD Design Journal
url: http://acli.github.io/INCD-Journal
baseurl: http://acli.github.io/INCD-Journal

# Short bio or description (displayed in the header)
description: This is a test. Please ignore.

