permalink: /:categories/:title.html
url: "http://anosognosia.github.io/INCD-Journal/"
baseurl: "http://anosognosia.github.io/INCD-Journal/"
full_name: "Edgar Wong Baxter Jr."
first_name: "Edgar"
last_name: "Wong Baxter Jr."
blog_title: "INCD-Journal"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: ""
copyright_year: "2015"
google_analytics_code: ""
aboutme: "An old book, boiled in oil"
twitter: "edgarwongbaxterjr"
github: "anosognosia"
facebook: "jamaicasdarling"
linkined_url: ""
